server:
  port: 8081

spring:
  rsocket:
    server:
      port: ${random.int[10000,60000]}
      transport: tcp
  redis:
    redisson:
      config: | 
        singleServerConfig:
          address: redis://127.0.0.1:6314
          password: 
          database: 0

boluo:
  im:
    originPatterns:
    localIp: 127.0.0.1
    groupUrl:
    authUrl: