server:
  port: 8081

spring:
  rsocket:
    server:
      port: 18081
      transport: tcp
  redis:
    redisson:
      config: | 
        singleServerConfig:
          address: redis://127.0.0.1:6314
          password: 
          database: 0

boluo:
  im:
    originPatterns:
    localIp: 127.0.0.1
    groupKeyTemplate: boluo:chat:tenant:{tenantId}:group:{groupId}:members
    groupUrl: http://127.0.0.1:9090/Tenants/Groups/Members
    authUrl: http://127.0.0.1:9090/validToken